### ISSUE TITLE
Save to database using async = true everywhere if possible

### ISSUE THREAD

**Issue by simernes** [dhis2/dhis2-android-sdk#10]
In DbFlow there is an option to save async true|false. When true, saving is added to a transaction queue and is executed in bulk. This is better for flow and is safer when multiple threads are saving simultaneously. Setting the flag to false may cause crashes due to db locks if two "synchronous" save calls happen at the same time from different threads.

If possible make sure async is always true.

**Comment by bobjolliffe** [comment]
Hi Simen

I'm no expert on DbFlow but it does seem that changing from a synchronous
mode (which might block ui threads) to an asynch one is a little more
complex than just changing a parameter.  Now the semantics are a little
different as the transactionmanager takes care of the eventual save - which
might or might not fail.  What mechanism is there in DbFlow to rendezvouz
eventually with the "completion event" so that the UI is able to respond to
if the save has worked or not?  It seems that to just fire and forget and
hope for the best is not going to be an adequate strategy.

There are some very real benefits to doing asynchronous I/O, particularly
in UI code, but it does come at a cost of complexity.  Having said that, I
am sure DbFlow has an elegant solution :-)

Bob

**Comment by bobjolliffe** [comment]
To answer my own question :
https://github.com/Raizlabs/DBFlow/blob/master/usage/ObservableModels.md

**Comment by simernes** [comment]
Yes exactly. It's a problem that we will have to deal with anyways because of data being synced in the background
